### ISSUE TITLE
The window of the plugin is too big for a small screen size.

### ISSUE THREAD

**Issue by ANN-4-BE-11-A** [ryanjamurphy/vantage-obsidian#4] opened 2021-04-29 17:38 UTC
**Problem**

The window of the plugin is too big for a small screen size.

**Expected behavior**

The window should wrap nicely into the Obsidian program.

**Details**

- [Screenshot of the issue](https://imgur.com/jIT0hp8).
- My screen size is 7.1 inches.
- My maximum screen resolution is 1366x768(16:9).
- I'm on Ubuntu 16.04 LTS.

**Comment by ryanjamurphy** [comment] 2021-05-12 18:50
Duplicate of #3 (which is now fixed as of 1.3.0)!

**Closed as completed by ryanjamurphy** 2021-05-12 18:50 UTC
